In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# Set up plotting style
plt.style.use('seaborn-v0_8')
sns.set_palette("husl")

#  Scalars and Vectors Implementation

In [2]:
class LinearAlgebraFundamentals:
    """Implementation of fundamental linear algebra concepts for ML"""
    
    def __init__(self):
        print("=== Linear Algebra for Machine Learning ===\n")
    
    def scalar_operations(self):
        """Demonstrate scalar operations"""
        print("1. SCALARS")
        print("-" * 30)
        
        # Learning rate example
        learning_rate = 0.01
        loss = 0.45
        
        print(f"Learning rate (scalar): {learning_rate}")
        print(f"Loss value (scalar): {loss}")
        print(f"Updated learning rate: {learning_rate * 0.99}")
        
        return learning_rate, loss
    
    def vector_operations(self):
        """Demonstrate vector operations"""
        print("\n2. VECTORS")
        print("-" * 30)
        
        # Create sample vectors
        weights = np.array([0.1, -0.2, 0.3, -0.1, 0.4])
        features = np.array([1.2, 0.8, -0.5, 1.1, 0.3])
        bias = np.array([0.01])
        
        print(f"Weights vector: {weights}")
        print(f"Features vector: {features}")
        print(f"Bias vector: {bias}")
        
        # Dot product (neural network forward pass)
        z = np.dot(weights, features) + bias
        print(f"Dot product (z = w·x + b): {z[0]:.3f}")
        
        return weights, features, z
    
    def distance_calculations(self):
        """Calculate various distances"""
        print("\n3. VECTOR DISTANCES")
        print("-" * 30)
        
        # Sample data points
        point_a = np.array([1, 2, 3])
        point_b = np.array([4, 5, 6])
        
        # Euclidean distance
        euclidean_dist = np.linalg.norm(point_a - point_b)
        print(f"Point A: {point_a}")
        print(f"Point B: {point_b}")
        print(f"Euclidean distance: {euclidean_dist:.3f}")
        
        # Distance from origin
        dist_origin_a = np.linalg.norm(point_a)
        dist_origin_b = np.linalg.norm(point_b)
        print(f"Distance from origin - A: {dist_origin_a:.3f}")
        print(f"Distance from origin - B: {dist_origin_b:.3f}")
        
        return point_a, point_b, euclidean_dist
    
    def vector_transformations(self):
        """Demonstrate vector transformations"""
        print("\n4. VECTOR TRANSFORMATIONS")
        print("-" * 30)
        
        original_vector = np.array([3, 4])
        
        # Scalar operations
        scaled_vector = 2 * original_vector
        shifted_vector = original_vector + 1
        
        print(f"Original vector: {original_vector}")
        print(f"Scaled (2x): {scaled_vector}")
        print(f"Shifted (+1): {shifted_vector}")
        
        # Unit vector
        unit_vector = original_vector / np.linalg.norm(original_vector)
        print(f"Unit vector: {unit_vector}")
        print(f"Magnitude of unit vector: {np.linalg.norm(unit_vector):.3f}")
        
        return original_vector, unit_vector
    
    def dot_product_application(self):
        """Demonstrate dot product applications"""
        print("\n5. DOT PRODUCT APPLICATIONS")
        print("-" * 30)
        
        # User preferences and item features
        user_pref = np.array([0.8, 0.2, 0.6])  # Action, Comedy, Drama
        movie_features = np.array([0.9, 0.1, 0.3])  # Movie characteristics
        
        similarity = np.dot(user_pref, movie_features)
        cosine_similarity = np.dot(user_pref, movie_features) / (
            np.linalg.norm(user_pref) * np.linalg.norm(movie_features)
        )
        
        print(f"User preferences: {user_pref}")
        print(f"Movie features: {movie_features}")
        print(f"Similarity score: {similarity:.3f}")
        print(f"Cosine similarity: {cosine_similarity:.3f}")
        
        # Angle between vectors
        angle_rad = np.arccos(np.clip(cosine_similarity, -1, 1))
        angle_deg = np.degrees(angle_rad)
        print(f"Angle between vectors: {angle_deg:.1f}°")
        
        return similarity, cosine_similarity

# Run linear algebra fundamentals
linalg = LinearAlgebraFundamentals()
learning_rate, loss = linalg.scalar_operations()
weights, features, z = linalg.vector_operations()
point_a, point_b, euclidean_dist = linalg.distance_calculations()
original_vector, unit_vector = linalg.vector_transformations()
similarity, cosine_sim = linalg.dot_product_application()

=== Linear Algebra for Machine Learning ===

1. SCALARS
------------------------------
Learning rate (scalar): 0.01
Loss value (scalar): 0.45
Updated learning rate: 0.0099

2. VECTORS
------------------------------
Weights vector: [ 0.1 -0.2  0.3 -0.1  0.4]
Features vector: [ 1.2  0.8 -0.5  1.1  0.3]
Bias vector: [0.01]
Dot product (z = w·x + b): -0.170

3. VECTOR DISTANCES
------------------------------
Point A: [1 2 3]
Point B: [4 5 6]
Euclidean distance: 5.196
Distance from origin - A: 3.742
Distance from origin - B: 8.775

4. VECTOR TRANSFORMATIONS
------------------------------
Original vector: [3 4]
Scaled (2x): [6 8]
Shifted (+1): [4 5]
Unit vector: [0.6 0.8]
Magnitude of unit vector: 1.000

5. DOT PRODUCT APPLICATIONS
------------------------------
User preferences: [0.8 0.2 0.6]
Movie features: [0.9 0.1 0.3]
Similarity score: 0.920
Cosine similarity: 0.946
Angle between vectors: 19.0°


# Matrix Operations Implementation

In [ ]:
class MatrixOperations:
    """Comprehensive matrix operations for ML"""
    
    
    
    def basic_matrix_operations(self):
        """Fundamental matrix operations"""
        print("\n1. BASIC MATRIX OPERATIONS")
        print("-" * 35)
        
        # Sample matrices
        A = np.array([[1, 2, 3], 
                      [4, 5, 6]])
        B = np.array([[2, 0, 1], 
                      [1, 2, 3]])
        weights = np.array([[0.1, 0.2], 
                           [0.3, 0.4], 
                           [0.5, 0.6]])
        
        print("Matrix A (2x3):")
        print(A)
        print("\nMatrix B (2x3):")
        print(B)
        print("\nWeight Matrix (3x2):")
        print(weights)
        
        # Matrix operations
        addition = A + B
        subtraction = A - B
        scalar_mult = 2 * A
        
        print(f"\nA + B:")
        print(addition)
        print(f"\nA - B:")
        print(subtraction)
        print(f"\n2 * A:")
        print(scalar_mult)
        
        return A, B, weights
    
    def matrix_multiplication(self, A, weights):
        """Matrix multiplication examples"""
        print("\n2. MATRIX MULTIPLICATION")
        print("-" * 35)
        
        # Neural network layer simulation
        input_data = np.array([[1, 2, 3], 
                              [4, 5, 6]])  # 2 samples, 3 features
        
        # Forward pass: input_data @ weights
        layer_output = np.dot(input_data, weights)
        
        print("Input data (2x3):")
        print(input_data)
        print("\nWeights (3x2):")
        print(weights)
        print("\nLayer output (2x2):")
        print(layer_output)
        
        # Transpose operations
        A_transpose = A.T
        print(f"\nA transpose:")
        print(A_transpose)
        
        return layer_output, A_transpose
    
    def special_matrices(self):
        """Demonstrate special matrix types"""
        print("\n3. SPECIAL MATRICES")
        print("-" * 35)
        
        # Identity matrix
        I = np.eye(3)
        print("Identity matrix (3x3):")
        print(I)
        
        # Diagonal matrix
        D = np.diag([1, 2, 3])
        print("\nDiagonal matrix:")
        print(D)
        
        # Symmetric matrix
        S = np.array([[2, 1, 3], 
                      [1, 4, 2], 
                      [3, 2, 5]])
        print("\nSymmetric matrix:")
        print(S)
        print(f"Is symmetric: {np.allclose(S, S.T)}")
        
        # Orthogonal matrix (rotation)
        theta = np.pi/4  # 45 degrees
        R = np.array([[np.cos(theta), -np.sin(theta)], 
                      [np.sin(theta), np.cos(theta)]])
        print("\nOrthogonal matrix (rotation):")
        print(R)
        print(f"Is orthogonal: {np.allclose(R @ R.T, np.eye(2))}")
        
        return I, D, S, R
    
    def matrix_properties(self, A, S):
        """Calculate matrix properties"""
        print("\n4. MATRIX PROPERTIES")
        print("-" * 35)
        
        # Determinant
        try:
            det_A = np.linalg.det(A)
            print(f"Determinant of A: {det_A}")
        except:
            print("A is not square, cannot compute determinant")
        
        det_S = np.linalg.det(S)
        print(f"Determinant of symmetric matrix: {det_S:.3f}")
        
        # Rank
        rank_A = np.linalg.matrix_rank(A)
        rank_S = np.linalg.matrix_rank(S)
        print(f"Rank of A: {rank_A}")
        print(f"Rank of symmetric matrix: {rank_S}")
        
        # Inverse
        try:
            S_inv = np.linalg.inv(S)
            print(f"\nInverse of symmetric matrix:")
            print(S_inv)
            print(f"S @ S_inv = I: {np.allclose(S @ S_inv, np.eye(3))}")
        except:
            print("Matrix is singular, no inverse exists")
        
        return det_S, rank_A, rank_S

# Run matrix operations
matrix_ops = MatrixOperations()
A, B, weights = matrix_ops.basic_matrix_operations()
layer_output, A_transpose = matrix_ops.matrix_multiplication(A, weights)
I, D, S, R = matrix_ops.special_matrices()
det_S, rank_A, rank_S = matrix_ops.matrix_properties(A, S)


MATRIX OPERATIONS FOR MACHINE LEARNING

1. BASIC MATRIX OPERATIONS
-----------------------------------
Matrix A (2x3):
[[1 2 3]
 [4 5 6]]

Matrix B (2x3):
[[2 0 1]
 [1 2 3]]

Weight Matrix (3x2):
[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]]

A + B:
[[3 2 4]
 [5 7 9]]

A - B:
[[-1  2  2]
 [ 3  3  3]]

2 * A:
[[ 2  4  6]
 [ 8 10 12]]

2. MATRIX MULTIPLICATION
-----------------------------------
Input data (2x3):
[[1 2 3]
 [4 5 6]]

Weights (3x2):
[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]]

Layer output (2x2):
[[2.2 2.8]
 [4.9 6.4]]

A transpose:
[[1 4]
 [2 5]
 [3 6]]

3. SPECIAL MATRICES
-----------------------------------
Identity matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Diagonal matrix:
[[1 0 0]
 [0 2 0]
 [0 0 3]]

Symmetric matrix:
[[2 1 3]
 [1 4 2]
 [3 2 5]]
Is symmetric: True

Orthogonal matrix (rotation):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Is orthogonal: True

4. MATRIX PROPERTIES
-----------------------------------
A is not square, cannot compute determinant
Determinan