Machine Learning Applications
Neural Networks: Matrix operations for forward/backward propagation

Sound Recognition: Acoustic monitoring and species tracking

AI Music Generation: Compressing music to discrete codes and generating new compositions

Image Compression: Reducing matrix rank for efficient storag

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Elimination Method for 2x2 Systems

In [2]:
def solve_2x2_system(a1, b1, c1, a2, b2, c2):
    """
    Solve system:
    a1*x + b1*y = c1
    a2*x + b2*y = c2
    """
    # Step 1: Make coefficient of x = 1 in first equation
    if a1 != 0:
        b1_norm = b1 / a1
        c1_norm = c1 / a1
        a1_norm = 1
    else:
        # If a1 is 0, swap equations
        return solve_2x2_system(a2, b2, c2, a1, b1, c1)
    
    # Step 2: Eliminate x from second equation
    if a2 != 0:
        factor = a2
        new_b2 = b2 - factor * b1_norm
        new_c2 = c2 - factor * c1_norm
        
        # Step 3: Solve for y
        if new_b2 != 0:
            y = new_c2 / new_b2
        else:
            if new_c2 == 0:
                return None, "Infinite solutions"
            else:
                return None, "No solution"
        
        # Step 4: Solve for x
        x = c1_norm - b1_norm * y
        
        return (x, y), "Unique solution"
    else:
        # Second equation has no x term
        if b2 != 0:
            y = c2 / b2
            x = c1_norm - b1_norm * y
            return (x, y), "Unique solution"
        else:
            if c2 == 0:
                return None, "Infinite solutions"
            else:
                return None, "No solution"

# Test examples
print("SOLVING 2x2 SYSTEMS")
print("=" * 50)

# Example 1: Unique solution
# 5a + b = 17
# 4a - 3b = 6
solution1, status1 = solve_2x2_system(5, 1, 17, 4, -3, 6)
print(f"System 1: 5a + b = 17, 4a - 3b = 6")
print(f"Status: {status1}")
if solution1:
    print(f"Solution: a = {solution1[0]:.1f}, b = {solution1[1]:.1f}")
print()

# Example 2: Another unique solution
# 2a + 5b = 46
# 8a + b = 32
solution2, status2 = solve_2x2_system(2, 5, 46, 8, 1, 32)
print(f"System 2: 2a + 5b = 46, 8a + b = 32")
print(f"Status: {status2}")
if solution2:
    print(f"Solution: a = {solution2[0]:.1f}, b = {solution2[1]:.1f}")
print()

SOLVING 2x2 SYSTEMS
System 1: 5a + b = 17, 4a - 3b = 6
Status: Unique solution
Solution: a = 3.0, b = 2.0

System 2: 2a + 5b = 46, 8a + b = 32
Status: Unique solution
Solution: a = 3.0, b = 8.0



# 3x3

In [4]:
def solve_3x3_system(A, b):
    """
    Solve 3x3 system Ax = b using elimination method
    """
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    
    print("Original system:")
    for i in range(3):
        print(f"{A[i,0]:.1f}a + {A[i,1]:.1f}b + {A[i,2]:.1f}c = {b[i]:.1f}")
    
    # Step 1: Make a coefficient = 1 in first equation
    if A[0,0] != 0:
        A[0] = A[0] / A[0,0]
        b[0] = b[0] / A[0,0]
    
    print("\nAfter normalizing first equation:")
    for i in range(3):
        print(f"{A[i,0]:.1f}a + {A[i,1]:.1f}b + {A[i,2]:.1f}c = {b[i]:.1f}")
    
    # Step 2: Eliminate a from second and third equations
    for i in range(1, 3):
        factor = A[i,0]
        A[i] = A[i] - factor * A[0]
        b[i] = b[i] - factor * b[0]
    
    print("\nAfter eliminating a from equations 2 and 3:")
    for i in range(3):
        print(f"{A[i,0]:.1f}a + {A[i,1]:.1f}b + {A[i,2]:.1f}c = {b[i]:.1f}")
    
    # Step 3: Make b coefficient = 1 in second equation
    if A[1,1] != 0:
        A[1] = A[1] / A[1,1]
        b[1] = b[1] / A[1,1]
    
    print("\nAfter normalizing second equation:")
    for i in range(3):
        print(f"{A[i,0]:.1f}a + {A[i,1]:.1f}b + {A[i,2]:.1f}c = {b[i]:.1f}")
    
    # Step 4: Eliminate b from third equation
    if A[2,1] != 0:
        factor = A[2,1]
        A[2] = A[2] - factor * A[1]
        b[2] = b[2] - factor * b[1]
    
    print("\nAfter eliminating b from third equation:")
    for i in range(3):
        print(f"{A[i,0]:.1f}a + {A[i,1]:.1f}b + {A[i,2]:.1f}c = {b[i]:.1f}")
    
    # Step 5: Solve for c, then b, then a
    if A[2,2] != 0:
        c = b[2] / A[2,2]
        b_val = b[1] - A[1,2] * c
        a_val = b[0] - A[0,1] * b_val - A[0,2] * c
        
        return (a_val, b_val, c), "Unique solution"
    else:
        if b[2] == 0:
            return None, "Infinite solutions"
        else:
            return None, "No solution"

# Example from slides
A = [[1, 1, 2], [3, -3, -1], [2, -1, 6]]
b = [12, 3, 24]

print("3x3 SYSTEM SOLVING DEMONSTRATION")
print("=" * 50)
solution, status = solve_3x3_system(A, b)
print(f"\nFinal status: {status}")
if solution:
    print(f"Solution: a = {solution[0]:.1f}, b = {solution[1]:.1f}, c = {solution[2]:.1f}")
    # Verify
    verification = np.dot(A, solution)
    print(f"Verification: A*x = {verification}, should equal {b}")

3x3 SYSTEM SOLVING DEMONSTRATION
Original system:
1.0a + 1.0b + 2.0c = 12.0
3.0a + -3.0b + -1.0c = 3.0
2.0a + -1.0b + 6.0c = 24.0

After normalizing first equation:
1.0a + 1.0b + 2.0c = 12.0
3.0a + -3.0b + -1.0c = 3.0
2.0a + -1.0b + 6.0c = 24.0

After eliminating a from equations 2 and 3:
1.0a + 1.0b + 2.0c = 12.0
0.0a + -6.0b + -7.0c = -33.0
0.0a + -3.0b + 2.0c = 0.0

After normalizing second equation:
1.0a + 1.0b + 2.0c = 12.0
-0.0a + 1.0b + 1.2c = -33.0
0.0a + -3.0b + 2.0c = 0.0

After eliminating b from third equation:
1.0a + 1.0b + 2.0c = 12.0
-0.0a + 1.0b + 1.2c = -33.0
0.0a + 0.0b + 5.5c = -99.0

Final status: Unique solution
Solution: a = 60.0, b = -12.0, c = -18.0
Verification: A*x = [ 12. 234.  24.], should equal [12, 3, 24]


# Redundant Systems (Infinite Solutions)

In [5]:
def analyze_singular_system(A, b):
    """
    Analyze singular systems - redundant or contradictory
    """
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    
    print("System analysis:")
    for i in range(len(b)):
        equation = " + ".join([f"{A[i,j]:.1f}x_{j+1}" for j in range(A.shape[1])])
        print(f"{equation} = {b[i]:.1f}")
    
    # Check if system is redundant
    rank_A = np.linalg.matrix_rank(A)
    augmented = np.column_stack((A, b))
    rank_augmented = np.linalg.matrix_rank(augmented)
    
    print(f"\nRank of A: {rank_A}")
    print(f"Rank of augmented matrix: {rank_augmented}")
    
    if rank_A == rank_augmented:
        if rank_A < A.shape[1]:
            print("System: REDUNDANT (Infinite solutions)")
            print(f"Degrees of freedom: {A.shape[1] - rank_A}")
            return "infinite"
        else:
            print("System: UNIQUE SOLUTION")
            return "unique"
    else:
        print("System: CONTRADICTORY (No solution)")
        return "none"

# Test singular systems
print("SINGULAR SYSTEMS ANALYSIS")
print("=" * 50)

# Redundant system
A_red = [[1, 1], [2, 2]]
b_red = [10, 20]
print("Redundant system:")
result1 = analyze_singular_system(A_red, b_red)
print()

# Contradictory system
A_contra = [[1, 1], [2, 2]]
b_contra = [10, 24]
print("Contradictory system:")
result2 = analyze_singular_system(A_contra, b_contra)
print()

# Another redundant system
A_red2 = [[5, 1], [10, 2]]
b_red2 = [11, 22]
print("Another redundant system:")
result3 = analyze_singular_system(A_red2, b_red2)

SINGULAR SYSTEMS ANALYSIS
Redundant system:
System analysis:
1.0x_1 + 1.0x_2 = 10.0
2.0x_1 + 2.0x_2 = 20.0

Rank of A: 1
Rank of augmented matrix: 1
System: REDUNDANT (Infinite solutions)
Degrees of freedom: 1

Contradictory system:
System analysis:
1.0x_1 + 1.0x_2 = 10.0
2.0x_1 + 2.0x_2 = 24.0

Rank of A: 1
Rank of augmented matrix: 2
System: CONTRADICTORY (No solution)

Another redundant system:
System analysis:
5.0x_1 + 1.0x_2 = 11.0
10.0x_1 + 2.0x_2 = 22.0

Rank of A: 1
Rank of augmented matrix: 1
System: REDUNDANT (Infinite solutions)
Degrees of freedom: 1


# Row Operations Class

In [6]:
def demonstrate_row_operations():
    """Demonstrate that row operations preserve singularity"""
    
    # Original non-singular matrix
    A_original = np.array([[5, 1], [4, -3]])
    det_original = np.linalg.det(A_original)
    
    print("ROW OPERATIONS AND SINGULARITY")
    print("=" * 50)
    print(f"Original matrix:\n{A_original}")
    print(f"Determinant: {det_original:.2f}")
    print(f"Singular: {abs(det_original) < 1e-10}")
    print()
    
    # Operation 1: Swapping rows
    A_swap = A_original.copy()
    A_swap[[0, 1]] = A_swap[[1, 0]]  # Swap rows
    det_swap = np.linalg.det(A_swap)
    
    print("After swapping rows:")
    print(f"Matrix:\n{A_swap}")
    print(f"Determinant: {det_swap:.2f}")
    print(f"Singular: {abs(det_swap) < 1e-10}")
    print(f"Determinant changed sign: {abs(det_original + det_swap) < 1e-10}")
    print()
    
    # Operation 2: Multiplying a row by scalar
    A_mult = A_original.copy()
    A_mult[0] = A_mult[0] * 10  # Multiply first row by 10
    det_mult = np.linalg.det(A_mult)
    
    print("After multiplying first row by 10:")
    print(f"Matrix:\n{A_mult}")
    print(f"Determinant: {det_mult:.2f}")
    print(f"Singular: {abs(det_mult) < 1e-10}")
    print(f"Determinant scaled by 10: {abs(det_mult - 10 * det_original) < 1e-10}")
    print()
    
    # Operation 3: Adding a row to another
    A_add = A_original.copy()
    A_add[1] = A_add[1] + A_add[0]  # Add first row to second
    det_add = np.linalg.det(A_add)
    
    print("After adding first row to second:")
    print(f"Matrix:\n{A_add}")
    print(f"Determinant: {det_add:.2f}")
    print(f"Singular: {abs(det_add) < 1e-10}")
    print(f"Determinant unchanged: {abs(det_add - det_original) < 1e-10}")
    print()
    
    # Test with singular matrix
    A_singular = np.array([[1, 1], [2, 2]])
    det_singular = np.linalg.det(A_singular)
    
    print("Singular matrix example:")
    print(f"Original matrix:\n{A_singular}")
    print(f"Determinant: {det_singular:.2f}")
    print(f"Singular: {abs(det_singular) < 1e-10}")
    print()
    
    # Row operations on singular matrix
    A_singular_swap = A_singular.copy()
    A_singular_swap[[0, 1]] = A_singular_swap[[1, 0]]
    det_singular_swap = np.linalg.det(A_singular_swap)
    
    print("After swapping rows (singular matrix):")
    print(f"Matrix:\n{A_singular_swap}")
    print(f"Determinant: {det_singular_swap:.2f}")
    print(f"Still singular: {abs(det_singular_swap) < 1e-10}")

demonstrate_row_operations()

ROW OPERATIONS AND SINGULARITY
Original matrix:
[[ 5  1]
 [ 4 -3]]
Determinant: -19.00
Singular: False

After swapping rows:
Matrix:
[[ 4 -3]
 [ 5  1]]
Determinant: 19.00
Singular: False
Determinant changed sign: True

After multiplying first row by 10:
Matrix:
[[50 10]
 [ 4 -3]]
Determinant: -190.00
Singular: False
Determinant scaled by 10: True

After adding first row to second:
Matrix:
[[ 5  1]
 [ 9 -2]]
Determinant: -19.00
Singular: False
Determinant unchanged: True

Singular matrix example:
Original matrix:
[[1 1]
 [2 2]]
Determinant: 0.00
Singular: True

After swapping rows (singular matrix):
Matrix:
[[2 2]
 [1 1]]
Determinant: 0.00
Still singular: True


# Understanding Rank

In [7]:
def rank_analysis_demonstration():
    """Comprehensive rank analysis"""
    
    matrices = [
        # Non-singular 2x2
        ("Non-singular 2x2", [[1, 1], [1, 2]]),
        # Singular 2x2 - redundant
        ("Singular 2x2 - redundant", [[1, 1], [2, 2]]),
        # Singular 2x2 - zero
        ("Singular 2x2 - zero", [[0, 0], [0, 0]]),
        # Non-singular 3x3
        ("Non-singular 3x3", [[1, 1, 1], [1, 2, 1], [1, 1, 2]]),
        # Rank 2 3x3
        ("Rank 2 3x3", [[1, 1, 1], [1, 1, 2], [1, 1, 3]]),
        # Rank 1 3x3
        ("Rank 1 3x3", [[1, 1, 1], [2, 2, 2], [3, 3, 3]]),
        # Rank 0 3x3
        ("Rank 0 3x3", [[0, 0, 0], [0, 0, 0], [0, 0, 0]])
    ]
    
    print("MATRIX RANK ANALYSIS")
    print("=" * 60)
    
    for name, matrix in matrices:
        A = np.array(matrix, dtype=float)
        rank = np.linalg.matrix_rank(A)
        det = np.linalg.det(A) if A.shape[0] == A.shape[1] else "N/A"
        rows, cols = A.shape
        
        print(f"\n{name}:")
        print(f"Matrix:\n{A}")
        print(f"Shape: {rows}x{cols}")
        print(f"Rank: {rank}")
        if det != "N/A":
            print(f"Determinant: {det:.2f}")
        print(f"Full rank: {rank == min(rows, cols)}")
        print(f"Singular: {rank < min(rows, cols)}")
        
        # Solution space dimension
        if rows == cols:
            solution_dim = cols - rank
            print(f"Solution space dimension: {solution_dim}")

rank_analysis_demonstration()

MATRIX RANK ANALYSIS

Non-singular 2x2:
Matrix:
[[1. 1.]
 [1. 2.]]
Shape: 2x2
Rank: 2
Determinant: 1.00
Full rank: True
Singular: False
Solution space dimension: 0

Singular 2x2 - redundant:
Matrix:
[[1. 1.]
 [2. 2.]]
Shape: 2x2
Rank: 1
Determinant: 0.00
Full rank: False
Singular: True
Solution space dimension: 1

Singular 2x2 - zero:
Matrix:
[[0. 0.]
 [0. 0.]]
Shape: 2x2
Rank: 0
Determinant: 0.00
Full rank: False
Singular: True
Solution space dimension: 2

Non-singular 3x3:
Matrix:
[[1. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
Shape: 3x3
Rank: 3
Determinant: 1.00
Full rank: True
Singular: False
Solution space dimension: 0

Rank 2 3x3:
Matrix:
[[1. 1. 1.]
 [1. 1. 2.]
 [1. 1. 3.]]
Shape: 3x3
Rank: 2
Determinant: 0.00
Full rank: False
Singular: True
Solution space dimension: 1

Rank 1 3x3:
Matrix:
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
Shape: 3x3
Rank: 1
Determinant: 0.00
Full rank: False
Singular: True
Solution space dimension: 2

Rank 0 3x3:
Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: 3x3

# Rank and Image Compression

In [8]:
def rank_compression_demo():
    """Demonstrate rank reduction for compression"""
    
    # Create a simple "image" matrix
    original = np.array([
        [1, 2, 3, 4],
        [2, 4, 6, 8],
        [3, 6, 9, 12],
        [4, 8, 12, 16]
    ], dtype=float)
    
    print("RANK AND COMPRESSION DEMONSTRATION")
    print("=" * 50)
    print("Original matrix (high redundancy):")
    print(original)
    print(f"Rank: {np.linalg.matrix_rank(original)}")
    print(f"Shape: {original.shape}")
    print()
    
    # Full rank matrix for comparison
    full_rank = np.array([
        [1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]
    ], dtype=float)
    
    print("Full rank matrix (no redundancy):")
    print(full_rank)
    print(f"Rank: {np.linalg.matrix_rank(full_rank)}")
    print(f"Shape: {full_rank.shape}")
    print()
    
    # Low-rank approximation
    print("Low-rank approximations:")
    for target_rank in [3, 2, 1]:
        # For demonstration, we'll create a simple low-rank matrix
        if target_rank == 3:
            approx = np.array([
                [1, 2, 3, 4],
                [2, 4, 6, 8],
                [3, 6, 9, 12],
                [3.9, 7.8, 11.7, 15.6]  # Slightly different from perfect multiple
            ])
        elif target_rank == 2:
            approx = np.array([
                [1, 2, 3, 4],
                [2, 4, 6, 8],
                [2, 4, 6, 8],
                [2, 4, 6, 8]
            ])
        else:  # rank 1
            approx = np.array([
                [1, 2, 3, 4],
                [1, 2, 3, 4],
                [1, 2, 3, 4],
                [1, 2, 3, 4]
            ])
        
        actual_rank = np.linalg.matrix_rank(approx)
        compression_ratio = (1 - (target_rank * (original.shape[0] + original.shape[1])) / 
                           (original.shape[0] * original.shape[1])) * 100
        
        print(f"Target rank: {target_rank}, Actual rank: {actual_rank}")
        print(f"Compression ratio: {compression_ratio:.1f}%")
        print(f"Matrix:\n{approx}")
        print()

rank_compression_demo()

RANK AND COMPRESSION DEMONSTRATION
Original matrix (high redundancy):
[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]
 [ 3.  6.  9. 12.]
 [ 4.  8. 12. 16.]]
Rank: 1
Shape: (4, 4)

Full rank matrix (no redundancy):
[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]
Rank: 4
Shape: (4, 4)

Low-rank approximations:
Target rank: 3, Actual rank: 1
Compression ratio: -50.0%
Matrix:
[[ 1.   2.   3.   4. ]
 [ 2.   4.   6.   8. ]
 [ 3.   6.   9.  12. ]
 [ 3.9  7.8 11.7 15.6]]

Target rank: 2, Actual rank: 1
Compression ratio: 0.0%
Matrix:
[[1 2 3 4]
 [2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]]

Target rank: 1, Actual rank: 1
Compression ratio: 50.0%
Matrix:
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]



In [9]:
class RowEchelonFormer:
    """Convert matrices to row echelon form"""
    
    def __init__(self, A):
        self.A = np.array(A, dtype=float)
        self.steps = []
    
    def to_row_echelon(self):
        """Convert to row echelon form with steps"""
        A = self.A.copy()
        m, n = A.shape
        pivot_row = 0
        
        self.steps.append(("Initial matrix", A.copy()))
        
        for col in range(n):
            if pivot_row >= m:
                break
                
            # Find pivot in current column
            pivot_index = -1
            for row in range(pivot_row, m):
                if abs(A[row, col]) > 1e-10:
                    pivot_index = row
                    break
            
            if pivot_index == -1:
                continue  # No pivot in this column
                
            # Swap if necessary
            if pivot_index != pivot_row:
                A[[pivot_row, pivot_index]] = A[[pivot_index, pivot_row]]
                self.steps.append((f"Swapped rows {pivot_row+1} and {pivot_index+1}", A.copy()))
            
            # Normalize pivot row
            pivot_val = A[pivot_row, col]
            if abs(pivot_val - 1) > 1e-10:
                A[pivot_row] = A[pivot_row] / pivot_val
                self.steps.append((f"Normalized row {pivot_row+1}", A.copy()))
            
            # Eliminate below
            for row in range(pivot_row + 1, m):
                if abs(A[row, col]) > 1e-10:
                    factor = A[row, col]
                    A[row] = A[row] - factor * A[pivot_row]
                    self.steps.append((f"Eliminated from row {row+1} using row {pivot_row+1}", A.copy()))
            
            pivot_row += 1
        
        return A
    
    def display_steps(self):
        """Display all steps of row echelon conversion"""
        print("ROW ECHELON FORM CONVERSION STEPS")
        print("=" * 50)
        
        for i, (description, matrix) in enumerate(self.steps):
            print(f"Step {i+1}: {description}")
            print(matrix)
            print(f"Rank (approx): {np.linalg.matrix_rank(matrix)}")
            print()

# Test with various matrices
print("ROW ECHELON FORM EXAMPLES")
print("=" * 50)

# Example 1: Non-singular matrix
A1 = [[5, 1], [4, -3]]
print("Example 1: Non-singular 2x2")
former1 = RowEchelonFormer(A1)
ref1 = former1.to_row_echelon()
former1.display_steps()

# Example 2: Singular matrix
A2 = [[5, 1], [10, 2]]
print("Example 2: Singular 2x2")
former2 = RowEchelonFormer(A2)
ref2 = former2.to_row_echelon()
former2.display_steps()

# Example 3: 3x3 system from earlier
A3 = [[1, 1, 2], [3, -3, -1], [2, -1, 6]]
print("Example 3: 3x3 system")
former3 = RowEchelonFormer(A3)
ref3 = former3.to_row_echelon()
former3.display_steps()

ROW ECHELON FORM EXAMPLES
Example 1: Non-singular 2x2
ROW ECHELON FORM CONVERSION STEPS
Step 1: Initial matrix
[[ 5.  1.]
 [ 4. -3.]]
Rank (approx): 2

Step 2: Normalized row 1
[[ 1.   0.2]
 [ 4.  -3. ]]
Rank (approx): 2

Step 3: Eliminated from row 2 using row 1
[[ 1.   0.2]
 [ 0.  -3.8]]
Rank (approx): 2

Step 4: Normalized row 2
[[ 1.   0.2]
 [-0.   1. ]]
Rank (approx): 2

Example 2: Singular 2x2
ROW ECHELON FORM CONVERSION STEPS
Step 1: Initial matrix
[[ 5.  1.]
 [10.  2.]]
Rank (approx): 1

Step 2: Normalized row 1
[[ 1.   0.2]
 [10.   2. ]]
Rank (approx): 1

Step 3: Eliminated from row 2 using row 1
[[1.  0.2]
 [0.  0. ]]
Rank (approx): 1

Example 3: 3x3 system
ROW ECHELON FORM CONVERSION STEPS
Step 1: Initial matrix
[[ 1.  1.  2.]
 [ 3. -3. -1.]
 [ 2. -1.  6.]]
Rank (approx): 3

Step 2: Eliminated from row 2 using row 1
[[ 1.  1.  2.]
 [ 0. -6. -7.]
 [ 2. -1.  6.]]
Rank (approx): 3

Step 3: Eliminated from row 3 using row 1
[[ 1.  1.  2.]
 [ 0. -6. -7.]
 [ 0. -3.  2.]]
Rank (app

# Rank from Row Echelon Form

In [10]:
def rank_from_echelon_form(A):
    """Calculate rank by counting pivots in row echelon form"""
    A_array = np.array(A, dtype=float)
    m, n = A_array.shape
    
    # Convert to row echelon form
    pivot_row = 0
    for col in range(n):
        if pivot_row >= m:
            break
            
        # Find pivot
        pivot_found = False
        for row in range(pivot_row, m):
            if abs(A_array[row, col]) > 1e-10:
                pivot_found = True
                # Swap if necessary
                if row != pivot_row:
                    A_array[[pivot_row, row]] = A_array[[row, pivot_row]]
                
                # Normalize (not strictly necessary for rank)
                pivot_val = A_array[pivot_row, col]
                A_array[pivot_row] = A_array[pivot_row] / pivot_val
                
                # Eliminate below
                for elim_row in range(pivot_row + 1, m):
                    factor = A_array[elim_row, col]
                    A_array[elim_row] = A_array[elim_row] - factor * A_array[pivot_row]
                
                pivot_row += 1
                break
    
    # Count pivots (non-zero rows)
    rank = 0
    for i in range(m):
        if np.any(abs(A_array[i]) > 1e-10):
            rank += 1
    
    return rank, A_array

# Test rank calculation
test_matrices = [
    ("Non-singular 2x2", [[5, 1], [4, -3]]),
    ("Singular 2x2", [[1, 1], [2, 2]]),
    ("Zero matrix", [[0, 0], [0, 0]]),
    ("Non-singular 3x3", [[1, 1, 1], [1, 2, 1], [1, 1, 2]]),
    ("Rank 2 3x3", [[1, 1, 1], [1, 1, 2], [1, 1, 3]]),
]

print("RANK CALCULATION FROM ROW ECHELON FORM")
print("=" * 50)

for name, matrix in test_matrices:
    rank_calculated, echelon_form = rank_from_echelon_form(matrix)
    rank_numpy = np.linalg.matrix_rank(matrix)
    
    print(f"\n{name}:")
    print(f"Original matrix:\n{matrix}")
    print(f"Row echelon form:\n{echelon_form}")
    print(f"Calculated rank: {rank_calculated}")
    print(f"NumPy rank: {rank_numpy}")
    print(f"Match: {rank_calculated == rank_numpy}")

RANK CALCULATION FROM ROW ECHELON FORM

Non-singular 2x2:
Original matrix:
[[5, 1], [4, -3]]
Row echelon form:
[[ 1.   0.2]
 [-0.   1. ]]
Calculated rank: 2
NumPy rank: 2
Match: True

Singular 2x2:
Original matrix:
[[1, 1], [2, 2]]
Row echelon form:
[[1. 1.]
 [0. 0.]]
Calculated rank: 1
NumPy rank: 1
Match: True

Zero matrix:
Original matrix:
[[0, 0], [0, 0]]
Row echelon form:
[[0. 0.]
 [0. 0.]]
Calculated rank: 0
NumPy rank: 0
Match: True

Non-singular 3x3:
Original matrix:
[[1, 1, 1], [1, 2, 1], [1, 1, 2]]
Row echelon form:
[[1. 1. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
Calculated rank: 3
NumPy rank: 3
Match: True

Rank 2 3x3:
Original matrix:
[[1, 1, 1], [1, 1, 2], [1, 1, 3]]
Row echelon form:
[[1. 1. 1.]
 [0. 0. 1.]
 [0. 0. 0.]]
Calculated rank: 2
NumPy rank: 2
Match: True


In [11]:
class ReducedRowEchelonFormer:
    """Convert matrices to reduced row echelon form"""
    
    def __init__(self, A, b=None):
        self.A = np.array(A, dtype=float)
        self.b = np.array(b, dtype=float) if b is not None else None
        self.steps = []
    
    def to_reduced_row_echelon(self):
        """Convert to reduced row echelon form"""
        A = self.A.copy()
        if self.b is not None:
            b = self.b.copy()
        else:
            b = None
            
        m, n = A.shape
        pivot_row = 0
        
        self.steps.append(("Initial", A.copy(), b.copy() if b is not None else None))
        
        # Forward elimination (row echelon form)
        for col in range(n):
            if pivot_row >= m:
                break
                
            # Find pivot
            pivot_index = -1
            for row in range(pivot_row, m):
                if abs(A[row, col]) > 1e-10:
                    pivot_index = row
                    break
            
            if pivot_index == -1:
                continue
                
            # Swap if necessary
            if pivot_index != pivot_row:
                A[[pivot_row, pivot_index]] = A[[pivot_index, pivot_row]]
                if b is not None:
                    b[[pivot_row, pivot_index]] = b[[pivot_index, pivot_row]]
                self.steps.append((f"Swap rows {pivot_row+1} and {pivot_index+1}", 
                                 A.copy(), b.copy() if b is not None else None))
            
            # Normalize pivot row
            pivot_val = A[pivot_row, col]
            A[pivot_row] = A[pivot_row] / pivot_val
            if b is not None:
                b[pivot_row] = b[pivot_row] / pivot_val
            self.steps.append((f"Normalize row {pivot_row+1}", 
                             A.copy(), b.copy() if b is not None else None))
            
            # Eliminate below and above
            for row in range(m):
                if row != pivot_row and abs(A[row, col]) > 1e-10:
                    factor = A[row, col]
                    A[row] = A[row] - factor * A[pivot_row]
                    if b is not None:
                        b[row] = b[row] - factor * b[pivot_row]
                    self.steps.append((f"Eliminate from row {row+1}", 
                                     A.copy(), b.copy() if b is not None else None))
            
            pivot_row += 1
        
        if b is not None:
            return A, b
        else:
            return A
    
    def display_steps(self):
        """Display all conversion steps"""
        print("REDUCED ROW ECHELON FORM CONVERSION")
        print("=" * 60)
        
        for i, (description, matrix, b_vec) in enumerate(self.steps):
            print(f"Step {i+1}: {description}")
            print("Matrix A:")
            print(matrix)
            if b_vec is not None:
                print("Vector b:")
                print(b_vec)
            print()

# Demonstration
print("REDUCED ROW ECHELON FORM DEMONSTRATION")
print("=" * 50)

# Example system
A = [[5, 1], [4, -3]]
b = [17, 6]

print("Original system:")
print("A =", A)
print("b =", b)
print()

reducer = ReducedRowEchelonFormer(A, b)
A_rref, b_rref = reducer.to_reduced_row_echelon()

print("Final Reduced Row Echelon Form:")
print("A_rref =")
print(A_rref)
print("b_rref =", b_rref)
print()

# Solution is directly readable from RREF
print("Solution from RREF:")
print(f"x₁ = {b_rref[0]:.1f}")
print(f"x₂ = {b_rref[1]:.1f}")

print("\nDetailed steps:")
reducer.display_steps()

REDUCED ROW ECHELON FORM DEMONSTRATION
Original system:
A = [[5, 1], [4, -3]]
b = [17, 6]

Final Reduced Row Echelon Form:
A_rref =
[[ 1.  0.]
 [-0.  1.]]
b_rref = [3. 2.]

Solution from RREF:
x₁ = 3.0
x₂ = 2.0

Detailed steps:
REDUCED ROW ECHELON FORM CONVERSION
Step 1: Initial
Matrix A:
[[ 5.  1.]
 [ 4. -3.]]
Vector b:
[17.  6.]

Step 2: Normalize row 1
Matrix A:
[[ 1.   0.2]
 [ 4.  -3. ]]
Vector b:
[3.4 6. ]

Step 3: Eliminate from row 2
Matrix A:
[[ 1.   0.2]
 [ 0.  -3.8]]
Vector b:
[ 3.4 -7.6]

Step 4: Normalize row 2
Matrix A:
[[ 1.   0.2]
 [-0.   1. ]]
Vector b:
[3.4 2. ]

Step 5: Eliminate from row 1
Matrix A:
[[ 1.  0.]
 [-0.  1.]]
Vector b:
[3. 2.]



# hudai 

In [15]:
class LinearSystemSolver:
    """Comprehensive linear system solver with all methods"""
    
    def __init__(self, A, b=None):
        self.A = np.array(A, dtype=float)
        self.b = np.array(b, dtype=float) if b is not None else None
        self.rank = None
        self.singular = None
        self.solution_type = None
        
    def analyze(self):
        """Complete system analysis"""
        self.rank = np.linalg.matrix_rank(self.A)
        rows, cols = self.A.shape
        
        if self.b is not None:
            augmented = np.column_stack((self.A, self.b))
            rank_augmented = np.linalg.matrix_rank(augmented)
            
            if self.rank == rank_augmented:
                if self.rank == cols:
                    self.solution_type = "unique"
                    self.singular = False
                else:
                    self.solution_type = "infinite"
                    self.singular = True
            else:
                self.solution_type = "none"
                self.singular = True
        else:
            # Homogeneous system
            if self.rank == cols:
                self.solution_type = "unique_zero"
                self.singular = False
            else:
                self.solution_type = "infinite"
                self.singular = True
    
    def solve(self):
        """Solve system using appropriate method"""
        self.analyze()
        
        if self.b is None:
            print("Homogeneous system Ax = 0")
            if self.solution_type == "unique_zero":
                return np.zeros(self.A.shape[1]), "Unique solution: x = 0"
            else:
                return None, f"Infinite solutions, nullity = {self.A.shape[1] - self.rank}"
        
        if self.solution_type == "unique":
            try:
                x = np.linalg.solve(self.A, self.b)
                return x, "Unique solution"
            except np.linalg.LinAlgError:
                # Use RREF as backup
                return self._solve_with_rref()
        elif self.solution_type == "infinite":
            return self._solve_with_rref()
        else:  # no solution
            return None, "No solution"
    
    def _solve_with_rref(self):
        """Solve using reduced row echelon form"""
        augmented = np.column_stack((self.A, self.b))
        reducer = ReducedRowEchelonFormer(self.A, self.b)
        A_rref, b_rref = reducer.to_reduced_row_echelon()
        
        if self.solution_type == "unique":
            # Solution is in b_rref
            return b_rref, "Unique solution (from RREF)"
        else:
            # Infinite solutions - return parametric form
            return self._parametric_solution(A_rref, b_rref)
    
    def _parametric_solution(self, A_rref, b_rref):
        """Find parametric solution for infinite solutions case"""
        m, n = A_rref.shape
        pivot_cols = []
        free_vars = []
        
        # Identify pivot columns
        for i in range(m):
            for j in range(n):
                if abs(A_rref[i, j] - 1) < 1e-10:
                    pivot_cols.append(j)
                    break
        
        # Identify free variables
        for j in range(n):
            if j not in pivot_cols:
                free_vars.append(j)
        
        # Construct parametric solution
        solution = {}
        solution['pivot_vars'] = pivot_cols
        solution['free_vars'] = free_vars
        solution['particular'] = np.zeros(n)
        solution['nullspace_basis'] = []
        
        # This is a simplified version - full implementation would
        # construct the complete parametric solution
        
        return solution, f"Infinite solutions, {len(free_vars)} free variables"
    
    def report(self):
        """Generate comprehensive report"""
        self.analyze()
        
        print("LINEAR SYSTEM ANALYSIS REPORT")
        print("=" * 60)
        print(f"Matrix A ({self.A.shape[0]}x{self.A.shape[1]}):")
        print(self.A)
        
        if self.b is not None:
            print(f"Vector b: {self.b}")
        
        print(f"\nRank of A: {self.rank}")
        print(f"Singular: {self.singular}")
        print(f"Solution type: {self.solution_type}")
        
        if self.solution_type == "infinite" and self.b is not None:
            print(f"Degrees of freedom: {self.A.shape[1] - self.rank}")
        
        # Solve and display solution
        solution, message = self.solve()
        print(f"\nSolution: {message}")
        if solution is not None:
            if isinstance(solution, np.ndarray):
                print(f"x = {solution}")
            elif isinstance(solution, dict):
                print("Parametric solution details:")
                print(f"Pivot variables: {solution['pivot_vars']}")
                print(f"Free variables: {solution['free_vars']}")

# Test the complete solver
print("COMPREHENSIVE LINEAR SYSTEM SOLVER")
print("=" * 60)

# Test cases
test_systems = [
    # Unique solution
    ([[5, 1], [4, -3]], [17, 6], "Unique solution"),
    # Infinite solutions
    ([[1, 1], [2, 2]], [10, 20], "Infinite solutions"),
    # No solution
    ([[1, 1], [2, 2]], [10, 24], "No solution"),
    # 3x3 unique
    ([[1, 1, 1], [1, 2, 1], [1, 1, 2]], [10, 15, 12], "3x3 unique"),
]

for A, b, description in test_systems:
    print(f"\n{description}:")
    print("-" * 40)
    solver = LinearSystemSolver(A, b)
    solver.report()
    print()

COMPREHENSIVE LINEAR SYSTEM SOLVER

Unique solution:
----------------------------------------
LINEAR SYSTEM ANALYSIS REPORT
Matrix A (2x2):
[[ 5.  1.]
 [ 4. -3.]]
Vector b: [17.  6.]

Rank of A: 2
Singular: False
Solution type: unique

Solution: Unique solution
x = [3. 2.]


Infinite solutions:
----------------------------------------
LINEAR SYSTEM ANALYSIS REPORT
Matrix A (2x2):
[[1. 1.]
 [2. 2.]]
Vector b: [10. 20.]

Rank of A: 1
Singular: True
Solution type: infinite
Degrees of freedom: 1

Solution: Infinite solutions, 1 free variables
Parametric solution details:
Pivot variables: [0]
Free variables: [1]


No solution:
----------------------------------------
LINEAR SYSTEM ANALYSIS REPORT
Matrix A (2x2):
[[1. 1.]
 [2. 2.]]
Vector b: [10. 24.]

Rank of A: 1
Singular: True
Solution type: none

Solution: No solution


3x3 unique:
----------------------------------------
LINEAR SYSTEM ANALYSIS REPORT
Matrix A (3x3):
[[1. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
Vector b: [10. 15. 12.]

Rank of A

In [ ]:
def visualize_2d_systems():
    """Visualize 2D systems and their solutions"""
    import matplotlib.pyplot as plt
    
    systems = [
        # Unique solution
        ([[2, 1], [1, -1]], [5, 1], "Unique Solution", 'blue'),
        # Infinite solutions
        ([[1, 2], [2, 4]], [3, 6], "Infinite Solutions", 'green'),
        # No solution
        ([[1, 1], [1, 1]], [2, 3], "No Solution", 'red'),
    ]
    
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    for idx, (A, b, title, color) in enumerate(systems):
        ax = axes[idx]
        A = np.array(A)
        b = np.array(b)
        
        # Plot lines
        x = np.linspace(-10, 10, 400)
        
        for i in range(2):
            if A[i, 1] != 0:  
                y = (b[i] - A[i, 0] * x) / A[i, 1]
                ax.plot(x, y, label=f'{A[i,0]}x + {A[i,1]}y = {b[i]}', 
                       color=color, linewidth=2)
            else:  # Vertical line
                x_val = b[i] / A[i, 0] if A[i, 0] != 0 else 0
                ax.axvline(x=x_val, label=f'{A[i,0]}x = {b[i]}', 
                          color=color, linewidth=2)
        
        # Mark solution if unique
        try:
            solution = np.linalg.solve(A, b)
            ax.plot(solution[0], solution[1], 'ro', markersize=10, 
                   label=f'Solution: ({solution[0]:.1f}, {solution[1]:.1f})')
        except:
            pass
        
        ax.set_xlim(-5, 5)
        ax.set_ylim(-5, 5)
        ax.axhline(0, color='black', linewidth=0.5)
        ax.axvline(0, color='black', linewidth=0.5)
        ax.grid(True, alpha=0.3)
        ax.set_title(title)
        ax.legend()
        ax.set_aspect('equal')
    
    plt.tight_layout()
    plt.show()


# visualize_2d_systems()

### Rank-Nullity Theorem:
rank(A) + nullity(A) = number of columns
### Solution Space Dimension:
dim(solution space) = n - rank(A)  (for Ax=0)
### System Consistency:
System Ax=b has solution iff rank(A) = rank([A|b])
